<div class="form-group col-sm-12 form-horizontal">
    <label class="col-sm-2 control-label">Выберите язык</label>

    <div class="col-sm-2">
        <div class="btn-group">
            <button class="btn btn-default" type="button">
                <?= $collection->getByAttributeValue($locale, 'locale')->getName(); ?>
            </button>
            <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button" aria-expanded="false">
                <span class="caret"></span>
            </button>

            <ul role="menu" class="dropdown-menu">
                <?php foreach($collection as $entity): ?>
                    <li>
                        <a href="<?= $this->url($route, [], ['query' => ['lang_id' => $entity->getId()]], true); ?>">
                            <?= $entity->getName(); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
